name: Build and Release Edgeble-6 Bookworm

on:
  push:
    branches:
      - main      

jobs:
  build:
    permissions: write-all
    name: Edgeble-6 Bookworm runner
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        chmod 600 ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/known_hosts 

        # Configure SSH to use this key for GitLab
        echo -e "Host gitlab.com\n\tIdentityFile ~/.ssh/id_rsa\n" >> ~/.ssh/config

        # Test the SSH connection (optional)
        ssh -T git@gitlab.com || echo "SSH connection test failed, but continuing..."

    - name: Set up Remote Docker
      uses: docker/setup-buildx-action@v1

    - name: Authenticate Docker Registry
      run: |
        echo "Decoded Docker Auth Config:"
        echo "${{ secrets.DOCKER_AUTH_CONFIG }}"
        decoded_config=$(echo -n "${{ secrets.DOCKER_AUTH_CONFIG }}" | base64 --decode)
        echo "$decoded_config" > $HOME/.docker/config.json
        cat $HOME/.docker/config.json    

    - name: Build builder
      run: |

        echo "Clone builder.."
        git clone git@gitlab.com:edgeble/core/bookworm/builder.git && cd builder

        # Set the github_action value
        github_action=true
        echo "The value of github_action is set to $github_action"

        # Insert github_action below the model key in the configuration file
        echo "Inserting github_action below the model key..."
        sed -i '/recipe: recipe.yaml/a \  github_action: '"$github_action" .config.yaml
        cat .config.yaml

        echo "Clone container.."
        rm -rf -v /tmp/edgeble-container
        git clone git@gitlab.com:edgeble/tools/edgeble-container.git /tmp/edgeble-container  
        sudo cp -v /tmp/edgeble-container/edgeble-* /usr/local/bin/ 
        sudo chmod +x /usr/local/bin/edgeble-*

        echo "Building Bookworm Core..."
        sudo apt-get update
        sudo apt install qemu-user-static
        sudo apt install binfmt-support
        export RUNNER="${GITHUB_RUN_NUMBER}"
        edgeble-container -b v2.02 -r $RUNNER bookworm

    - name: Upload output artifacts
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v2.02"
        body: |
          - Summary:
            ```
            - FIrefly ITX-3588
            - Fix Display GDM
            ```
          - SD
            ```
            sudo bmaptool copy --bmap edgeble-6b_bookworm_kde_v2.02.bmap edgeble-6b_bookworm_kde_v2.02.img.gz /dev/sdX
            ```
          - eMMC
            ```
            - boot from SD
            - use u-boot 'ums 0 mmc 0'
            - Program eMMC from host same like MicroSD
            ```
        files: |
          ${{ github.workspace }}/builder/edgeble-6b_bookworm_kde_v2.02.ospack.tar.gz
          ${{ github.workspace }}/builder/edgeble-6b_bookworm_kde_v2.02.deskpack.tar.gz
          ${{ github.workspace }}/builder/edgeble-6b_bookworm_kde_v2.02.winpack.tar.gz
          ${{ github.workspace }}/builder/edgeble-6b_bookworm_kde_v2.02.core_testpack.tar.gz
          ${{ github.workspace }}/builder/edgeble-6b_bookworm_kde_v2.02.bmap
          ${{ github.workspace }}/builder/edgeble-6b_bookworm_kde_v2.02.img.gz
      env:
        GITHU_TOKEN: ${{ secrets.GITHUB_TOKEN }}
